name: Frontend deploy action
description: 'downloads artifact and deploys to AWS s3'

inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS_ACCESS_KEY_ID secret'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS_SECRET_ACCESS_KEY secret'
    required: true
  bucket_name:
    description: 'build.outputs.bucket_name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build_result

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to AWS
      run: |
        aws configure set default.s3.max_concurrent_requests 50
        aws s3 rm s3://ec-admins/${{ inputs.bucket_name }} --recursive  
        aws s3 sync ./ s3://ec-admins/${{ inputs.bucket_name }} --cache-control max-age=31536000 --exclude "index.html"
        aws s3 sync ./ s3://ec-admins/${{ inputs.bucket_name }} --cache-control max-age=0 --exclude "*" --include "index.html"
      shell: bash